// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CustomKeyboard
{
	
	
	public partial class Resource
	{
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_bottom = 2130968576;
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int sym_keyboard_delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int sym_keyboard_feedback_return = 2130837506;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int LinearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int container = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int keyboard_view = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int target = 2131165187;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int keyboard2 = 2131034112;
			
			private Xml()
			{
			}
		}
	}
}
